### ISSUE TITLE
Iteration 2 - Basic functionality of common errors

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#31]
Amend this issue as necessary.

## Some Inspiration

This is what LLVM prints out for a syntax error:

![screenshot 2015-03-31 16 03 57](https://cloud.githubusercontent.com/assets/77495/6930337/8f156e6a-d7bf-11e4-9d14-072c9bb93713.png)

This is what Swift prints out for a TypeError.

![swift-error-messages](https://cloud.githubusercontent.com/assets/77495/6930374/e0b206a2-d7bf-11e4-824d-4f4cf23539d6.png)

## Refactor / Refurbish the formatter

To ease the effort of adding errors, and not build too much on top of a shaky foundation, we will need better formatting code. We should also switch from CodeRay to Rouge before we start building on top of their particular nuances.

- [x] [Switch from CodeRay to Rouge](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/36)
- [x] [Better abstractions in the formatting code](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/33)

## The Errors

Each of these should include information useful for that particular error. Our goal is not to handle every case they come up, but to identify at least one common scenario and use a heuristic to help the developer get the feedback that is likely useful for them.

**Note: [Here](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/compare/0683606...bb351fe) is how to currently add a heuristic.**

- [x] [RuntimeError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/20)

  ![screenshot 2015-05-29 15 09 59](https://cloud.githubusercontent.com/assets/77495/7892840/287e3fe0-0615-11e5-9116-29d07472cfe2.png)
- [x] [SyntaxError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/8)

  ![screenshot 2015-05-29 16 14 10](https://cloud.githubusercontent.com/assets/77495/7893732/d191ea20-061d-11e5-8ac5-851199297c1a.png)
- [x] [LoadError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/6#issuecomment-106832205)

  ![screenshot 2015-05-29 15 14 24](https://cloud.githubusercontent.com/assets/77495/7892872/73d0fdac-0615-11e5-841d-f764c9da0656.png)
- [x] [ArgumentError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/2)

  ![screenshot 2015-05-29 15 16 53](https://cloud.githubusercontent.com/assets/77495/7892932/c68e5120-0615-11e5-8969-86808090e588.png)
- [x] [NameError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/16) / [NoMethodError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/1) (these two are similar enough, at present, that I just had the NameError use the NoMethodError that @bwvoss wrote)

  ![screenshot 2015-05-29 15 15 55](https://cloud.githubusercontent.com/assets/77495/7892898/b2b6aec2-0615-11e5-8f6e-ae9abe5e2bdc.png)

## Added

- [x] [Bug in ArgumentError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/37)
- [x] [Mark the current line when rendering code](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/41). Not in love with this solution, but it will suffice for now. The `2:` is highlighted in red to identify it as the line with the error.

  ![screenshot 2015-05-29 15 09 59](https://cloud.githubusercontent.com/assets/77495/7892840/287e3fe0-0615-11e5-9116-29d07472cfe2.png)

**Comment by JoshCheek** [comment]
Released version [0.0.2](https://rubygems.org/gems/what_weve_got_here_is_an_error_to_communicate/versions/0.0.2)
